#!/bin/bash

REMOTE_PATH="/c/Users/makwetjat/remote-scripts"

files=( "$REMOTE_PATH/run-remote-scripts/"*.sh )

PS3='Select remote script to run or 0 to exit: '
select file in "${files[@]}"; do
    if [[ $REPLY == "0" ]]; then
        echo 'Bye!' >&2
        exit
    elif [[ -z $file ]]; then
        echo 'Invalid choice, try again' >&2
    else
        COMMAND_SCRIPT="$file"  # Assign the selected script
        break
    fi
done

echo "Selected script: $COMMAND_SCRIPT"

echo $COMMAND_SCRIPT
